config/routes.rb
Rails.application.routes.draw do
  if Rails.env.development?
    mount GraphiQL::Rails::Engine, at: "/graphiql", graphql_path: "/graphql"
  end
  post "/graphql", to: "graphql#execute"
  root to: 'activities#index'

  resources :activities
  resources :categories
  resources :shelves

  resources :series, only: [:index, :show]
  resources :movies, only: [:index, :show]

  resources :search, only: [:index]
end

app/models/activity.rb
class Activity < ApplicationRecord
  belongs_to :category, optional: true
  belongs_to :shelf, optional: true

  validates :name, presence: true
  validates :description, presence: true
end

# == Schema Information
#
# Table name: activities
#
#  id          :integer          not null, primary key
#  kind        :integer
#  name        :string
#  description :text
#  category_id :integer
#  shelf_id    :integer
#  tags        :string
#  author      :string
#  cover       :string
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#
# Indexes
#
#  index_activities_on_category_id  (category_id)
#  index_activities_on_shelf_id     (shelf_id)
#
# Foreign Keys
#
#  category_id  (category_id => categories.id)
#  shelf_id     (shelf_id => shelves.id)
#

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :activities

  validates :name, presence: true

  # Mira la documentación sobre los macros broadcast_to_x en
  # https://rubydoc.info/github/hotwired/turbo-rails/Turbo/Broadcastable/ClassMethods
  #
  # En la documentación en el código fuente se encuentran los broadcast_X_to
  # https://github.com/hotwired/turbo-rails/blob/main/app/models/concerns/turbo/broadcastable.rb
  after_create_commit { broadcast_append_to "categories" }
  after_update_commit { broadcast_replace_to "categories" }
end

# == Schema Information
#
# Table name: categories
#
#  id          :integer          not null, primary key
#  name        :string
#  description :string
#  cover       :string
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#

app/models/shelf.rb
class Shelf < ApplicationRecord
  has_many :activities

  validates :name, presence: true

  after_create_commit { broadcast_append_to "shelves" }
  after_update_commit { broadcast_replace_to "shelves" }
end

# == Schema Information
#
# Table name: shelves
#
#  id          :integer          not null, primary key
#  name        :string
#  description :string
#  cover       :string
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#

app/controllers/activities_controller.rb
class ActivitiesController < ApplicationController
  def index
    @activities = Activity.order(created_at: :desc)
  end

  def new
    @activity = Activity.new
  end

  def create
    @activity = Activity.new(activity_params)

    if @activity.save
      redirect_to activities_path
    else
      render :new
    end
  end

  def edit
    @activity = Activity.find(params[:id])
  end

  def update
    @activity = Activity.find(params[:id])

    if @activity.update(activity_params)
      redirect_to activities_url, notice: 'Actividad actualizada'
    else
      render :edit
    end
  end

  def show
    @activity = Activity.find(params[:id])
  end

  private

  def activity_params
    params.require(:activity).permit(:name, :description, :cover, :tags, :author, :category_id, :shelf_id)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def index
    @categories = Category.all
    @category = Category.new
  end

  def new
    @category = Category.new
  end

  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to categories_url, notice: 'Categoría creada' }
      else
        format.html { render :new }

        # Esta es la forma en que le decimos a ActionCable cómo transmitir
        # el formulario de nuevo pero con los errores incluídos al turbo_frame_tag
        # correcto.
        #
        # Para la acción exitosa no es necesario.
        format.turbo_stream do
          render(
            turbo_stream: turbo_stream.replace(
              @category,
              partial: 'categories/form',
              locals: { category: @category }
            )
          )
        end
      end
    end
  end

  def edit
    @category = Category.find(params[:id])
  end

  def update
    @category = Category.find(params[:id])

    if @category.update(category_params)
      redirect_to categories_url, notice: 'Categoría actualizada'
    else
      render :edit
    end
  end

  def show
    @category = Category.find(params[:id])
  end

  private

  def category_params
    params.require(:category).permit(:name, :description, :cover)
  end
end

app/controllers/graphql_controller.rb
class GraphqlController < ApplicationController
  # If accessing from outside this domain, nullify the session
  # This allows for outside API access while preventing CSRF attacks,
  # but you'll have to authenticate your user separately
  # protect_from_forgery with: :null_session

  def execute
    variables = prepare_variables(params[:variables])
    query = params[:query]
    operation_name = params[:operationName]
    context = {
      # Query context goes here, for example:
      # current_user: current_user,
    }
    result = LeisureShelfPlaygroundSchema.execute(query, variables: variables, context: context, operation_name: operation_name)
    render json: result
  rescue StandardError => e
    raise e unless Rails.env.development?
    handle_error_in_development(e)
  end

  private

  # Handle variables in form data, JSON body, or a blank value
  def prepare_variables(variables_param)
    case variables_param
    when String
      if variables_param.present?
        JSON.parse(variables_param) || {}
      else
        {}
      end
    when Hash
      variables_param
    when ActionController::Parameters
      variables_param.to_unsafe_hash # GraphQL-Ruby will validate name and type of incoming variables.
    when nil
      {}
    else
      raise ArgumentError, "Unexpected parameter: #{variables_param}"
    end
  end

  def handle_error_in_development(e)
    logger.error e.message
    logger.error e.backtrace.join("\n")

    render json: { errors: [{ message: e.message, backtrace: e.backtrace }], data: {} }, status: 500
  end
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  # skip_before_action :prevent_htmx!

  def index
    @movies = Category.find_by(name: 'Películas')&.activities
  end

  def show
    # prevent_htmx!

    @movie = Activity.find(params[:id])

    respond_to do |format|
      format.html
    end
  end
end

app/controllers/search_controller.rb
class SearchController < ApplicationController
  def index
    @activities = if params[:query].present?
                    Activity.where("LOWER(name) LIKE '%#{params[:query]}%'")
                  else
                    Activity.order(created_at: :desc)
                  end

    respond_to do |format|
      format.html do
        render 'activities/index'
      end
    end
  end
end

app/controllers/series_controller.rb
class SeriesController < ApplicationController
  def index
    @series = Category.find_by(name: 'Series')&.activities
  end

  def show
    @serie = Activity.find(params[:id])
  end
end

app/controllers/shelves_controller.rb
class ShelvesController < ApplicationController
  def index
    @shelves = Shelf.all
    @shelf = Shelf.new
  end

  def show
    @shelf = Shelf.find(params[:id])
  end

  def new
    @shelf = Shelf.new
  end

  def create
    @shelf = Shelf.new(shelf_params)

    respond_to do |format|
      if @shelf.save
        format.html { redirect_to shelves_url, notice: 'Estante creado' }
      else
        format.html { render :new }

        format.turbo_stream do
          render(
            turbo_stream: turbo_stream.replace(
              @shelf,
              partial: 'shelves/form',
              locals: { shelf: @shelf }
            )
          )
        end
      end
    end
  end

  def edit
    @shelf = Shelf.find(params[:id])
  end

  def update
    @shelf = Shelf.find(params[:id])

    if @shelf.update(shelf_params)
      redirect_to shelves_url, notice: 'Estante actualizado'
    else
      render :edit
    end
  end

  private

  def shelf_params
    params.require(:shelf).permit(:name, :description, :cover)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def add_form_toggle_controller(params)
    return "data-controller=form-toggle" if ['categories', 'shelves'].include?(params[:controller])
  end
end

app/views/activities/_form.html.erb
<% content_for :top_text do %>
  <h3>Nueva Actividad</h3>
<% end %>

<% content_for :action_button do %>
  <%= link_to 'Volver', activities_path, class: 'bg-blue-500 hover:bg-blue-dark text-white font-bold py-2 px-4 rounded' %>
<% end %>

<%= form_with(model: @activity, local: true, data: { turbo: false }) do |f| %>
  <% if @activity.errors.any? %>
    <div id="error_explanation">
      <p>
        <%= pluralize(@activity.errors.count, "error") %> prohibited this category from being saved:
      </p>

      <ul class="list-disc text-red-500 mb-4">
        <% @activity.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="flex flex-row justify-center">
    <div class="flex flex-col flex-grow">
      <%= f.label :name %>
      <%= f.text_field :name, class: 'border-solid border-2 p-2 w-full md:w-3/4 lg:w-5/12', placeholder: 'Nombre' %>
    </div>

    <div class="flex flex-col flex-grow">
      <%= f.label :author %>
      <%= f.text_field :author, class: 'border-solid border-2 p-2 w-full md:w-3/4 lg:w-5/12', placeholder: 'Autor' %>
    </div>

    <div class="flex flex-col flex-grow">
      <%= f.label :tags %>
      <%= f.text_field :tags, class: 'border-solid border-2 p-2 w-full md:w-3/4 lg:w-5/12', placeholder: 'Etiquetas' %>
    </div>
  </div>

  <div class="flex flex-row justify-center mt-6">
    <div class="flex flex-col flex-grow">
      <%= f.label :category_id, 'Categoría' %>
      <%= f.collection_select(:category_id, Category.all, :id, :name, { include_blank: 'Escoge' }, { selected: @activity.category_id }) %>
    </div>

    <div class="flex flex-col flex-grow">
      <%= f.label :shelf_id, 'Estante' %>
      <%= f.collection_select(:shelf_id, Shelf.all, :id, :name, { include_blank: 'Escoge' }, { selected: @activity.category_id }) %>
    </div>
  </div>

  <div class="flex flex-row justify-center mt-6">
    <div class="flex flex-col flex-grow">
      <%= f.label :description %>
      <%= f.text_area :description, class: 'border-solid border-2 p-2 w-full md:w-3/4 lg:w-5/12', placeholder: 'Text' %>
    </div>
  </div>

  <div class="flex flex-row justify-center mt-4">
    <% button_text = @activity.new_record? ? 'Guardar' : 'Actualizar' %>
    <%= f.submit button_text, class: 'mt-2 bg-blue-500 text-white font-semibold px-4 py-2 rounded w-full md:w-3/4 lg:w-5/12' %>
  </div>
<% end %>

app/views/activities/edit.html.erb
<%= render 'form' %>

app/views/activities/index.html.erb
<% content_for :top_text do %>
  <h1>Todas las actividades</h1>
<% end %>

<% content_for :action_button do %>
  <!-- Usando HTMX

  Pongo el input aquí porque si lo pongo por fuera, cada vez que se renderice un resultado
  se repetirá de nuevo.

  Esto porque está trayendo todo lo que haya en la vista activities#index -->
  <input class="form-control" type="search" name="query" placeholder="Escribe para buscar"
    hx-get="/search"
    hx-trigger="keyup changed delay:500ms, query"
    hx-target="#activities">

  <%= link_to 'Crear Actividad', new_activity_path, class: 'bg-blue-500 hover:bg-blue-dark text-white font-bold py-2 px-4 rounded' %>
<% end %>

<div class="flex flex-row flex-wrap" id="activities">
  <%= render(ActivityCardComponent.with_collection(@activities)) %>
</div>

app/views/activities/new.html.erb
<%= render 'form' %>

app/views/activities/show.html.erb
<% content_for :top_text do %>
  <h2>Viendo: <%= @activity.name %></h2>
<% end %>

<% content_for :action_button do %>
  <%= link_to 'Volver', activities_path, class: 'bg-blue-500 hover:bg-blue-600 text-white font-bold py-2 px-4 rounded' %>
  <%= link_to 'Editar', edit_activity_path(@activity), class: 'bg-yellow-500 hover:bg-yellow-600 text-white font-bold py-2 px-4 rounded' %>
<% end %>

<div class="flex flex-row">
  <%= render(ActivityComponent.new(activity: @activity)) %>
</div>

app/views/categories/_category.html.erb
<!--
  Cuando queremos editar la categoría, podemos cargar el formulario en el mismo bloque HTML sin recargar la página.

  Para que la actualización funcione se necesita el `turbo_frame_tag` aquí y
  el `dom_id(category)` para que genere en el HTML `id=category_1`.

  Va de la mano con lo que está en el modelo Category callback `after_update_commit`.
-->
<%= turbo_frame_tag dom_id(category) do %>
  <div class="max-w-xs rounded overflow-hidden my-2 mr-2 bg-gray-200">
    <div class="px-6 py-4">
      <span class="name font-bold text-xl">
        <%= link_to category.name, category_path(category), data: { turbo: false } %>
      </span>
      <small>
        <%= link_to 'Edit', edit_category_path(category) %>
      </small>
    </div>
  </div>
<% end %>

app/views/categories/_form.html.erb
<%= form_with(model: category, id: dom_id(category)) do |f| %>
  <% if @category.errors.any? %>
    <div id="error_explanation">
      <p>
        <%= pluralize(@category.errors.count, "error") %> prohibited this category from being saved:
      </p>

      <ul class="list-disc text-red-500 mb-4">
        <% @category.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="flex flex-row justify-center">
    <div class="flex flex-col flex-grow">
      <%= f.label :name %>
      <%= f.text_field :name, class: 'border-solid border-2 p-2 w-full md:w-3/4 lg:w-5/12', placeholder: 'Nombre' %>
    </div>
  </div>

  <div class="flex flex-row justify-center mt-6">
    <div class="flex flex-col flex-grow">
      <%= f.label :description %>
      <%= f.text_area :description, class: 'border-solid border-2 p-2 w-full md:w-3/4 lg:w-5/12', placeholder: 'Text' %>
    </div>
  </div>

  <div class="flex flex-row mt-4">
    <% button_text = @category.new_record? ? 'Guardar' : 'Actualizar' %>
    <%= f.submit button_text, class: 'mt-2 bg-blue-500 text-white font-semibold px-4 py-2 rounded w-full md:w-3/4 lg:w-5/12 cursor-pointer' %>
  </div>
<% end %>

app/views/categories/edit.html.erb
<!--
  Cuando turbo falle el botón de editar categoría hará una navegación a esta vista.

  En ese caso, se cargará el `content_for` definido aquí.
-->
<% content_for :top_text do %>
  <h2>Editando categoría</h2>
<% end %>

<!--
  Este turbo_frame_tag se necesita para poder mostrar el formulario en el mismo lugar donde está el elemento a editar.
-->
<%= turbo_frame_tag dom_id(@category) do %>
  <%= render 'form', category: @category %>
<% end %>

app/views/categories/index.html.erb
<% content_for :top_text do %>
  <h3>Todas las categorías</h3>
<% end %>

<% content_for :action_button do %>
  <button
   class="bg-blue-500 hover:bg-blue-dark text-white font-bold py-2 px-4 rounded"
   data-action="click->form-toggle#toggle"
   data-target="form-toggl.form"
  >
    Crear Categoría
  </button>
<% end %>

<!--
  Este turbo_stream_from es necesario para que cuando se complete la acción del formulario y se cree un nuevo recurso se añada el mismo al listado y se refleje inmediatamente.

  Sin esto, todo funcionaría igual pero no habría cambio en la vista.

  Va de la mano con lo que se configura en el modelo Category, en el callback after_create_commit.
-->
<%= turbo_stream_from "categories" %>

<!-- Este turbo_frame_tag está aquí para poder hacer que se muestren los errores al ser una vista en un lugar
diferente. -->
<%= turbo_frame_tag "category_form" do %>
  <div data-form-toggle-target="form" class="hidden">
    <%= render "form", category: @category %>
  </div>
<% end %>

<div>
  <%= turbo_frame_tag "categories", class: "flex flex-row flex-wrap" do %>
    <%= render @categories %>

    <%#= render(CategoryComponent.with_collection(@categories)) %>
  <% end %>
</div>

app/views/categories/new.html.erb
<!--
  Cuando turbo falle el botón de nueva categoría hará una navegación a esta vista.

  En ese caso, se cargará el `content_for` definido aquí.
-->
<% content_for :top_text do %>
  <h2>Creando nueva categoría</h2>
<% end %>

<%= render 'form', category: @category %>

app/views/categories/show.html.erb
<% content_for :top_text do %>
  <h2>Viendo: <%= @category.name %></h2>
<% end %>

<% content_for :action_button do %>
  <%= link_to 'Volver', categories_path, class: 'bg-blue-500 hover:bg-blue-600 text-white font-bold py-2 px-4 rounded' %>
  <%= link_to 'Editar', edit_category_path(@category), class: 'bg-yellow-500 hover:bg-yellow-600 text-white font-bold py-2 px-4 rounded' %>
<% end %>

<div class="flex flex-col">
  <%= render(CategoryDetailComponent.new(category_detail: @category)) %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Leisure Shelf Playground</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= javascript_importmap_tags %>

    <script src="https://unpkg.com/htmx.org@1.9.3" integrity="sha384-lVb3Rd/Ca0AxaoZg5sACe8FJKF0tnUgR2Kd7ehUOG5GCcROv5uBIZsOqovBAcWua" crossorigin="anonymous"></script>
  </head>

  <body>
    <div class="w-full border shadow bg-white">
      <div class="flex min-h-screen">
        <%= render 'shared/sidebar' %>
        <!--
          Con el helper add_form_toggle_controller estoy definiendo, según necesito, en que vista definir el atributo data-controller.

          Sin eso, nada de lo de Stimulus funcionará.
        -->
        <div class="w-full flex flex-col" <%= add_form_toggle_controller(params) %>>
          <%= render 'shared/topbar' %>

          <!-- <div class="px-6 py-4 flex-1"> -->
          <div class="px-6 py-4 flex-1" hx-target="this">
            <%= yield %>
          </div>
        </div>
      </div>
    </div>
  </body>
</html>

app/views/movies/_movie.html.erb
<%#= link_to movies_path(movie.id) do %>
<!-- <a hx-get="/movies/<%= movie.id %>"> -->
<a hx-get="/movies/<%= movie.id %>" hx-push-url="true">
  <div class="max-w-xs rounded overflow-hidden my-2 mr-2 bg-gray-200">
    <%= image_tag('books.jpg', class: 'w-full h-32') %>

    <div class="px-6 py-4">
      <div class="name font-bold text-xl mb-2">
        <%= movie.name %>
      </div>

      <p class="text-grey-darker text-base">
        <%= movie.description %>
      </p>
    </div>

  </div>
</a>
<%# end %>

app/views/movies/index.html.erb
<% content_for :top_text do %>
  <h2>Películas</h2>
<% end %>

<div class="flex flex-row flex-wrap">
  <%= render partial: 'movie', collection: @movies, as: 'movie' %>
</div>

app/views/movies/show.html.erb
<div class="flex flex-col w-3/5">
  <h2 class="text-3xl"><%= @movie.name %></h2>
  <small><%= @movie.author %></small>

  <p class="my-4"><%= @movie.description %></p>
</div>

<div class="">
  <%= image_tag('books.jpg') %>
</div>

app/views/series/_serie.html.erb
<%= link_to series_path(serie.id) do %>
  <div class="max-w-xs rounded overflow-hidden my-2 mr-2 bg-gray-200">
    <%= image_tag('books.jpg', class: 'w-full h-32') %>
    <div class="px-6 py-4">
      <div class="name font-bold text-xl mb-2">
        <%= serie.name %>
      </div>
      <p class="text-grey-darker text-base">
        <%= serie.description %>
      </p>
    </div>
  </div>
<% end %>

app/views/series/index.html.erb
<% content_for :top_text do %>
  <h2>Series de TV</h2>
<% end %>

<div class="flex flex-row flex-wrap">
  <% if @series %>
    <!-- Renderizado con ERB -->
    <%#= render partial: 'serie', collection: @series, as: 'serie' %>

    <!-- Renderizado con Phlex -->
    <%= render Series.new(series: @series) %>
  <% else %>
    <p>Nada que ver por aquí.</p>
  <% end %>
</div>

app/views/shared/_sidebar.html.erb
<!-- Sidebar -->
<div class="bg-purple-900 bg-opacity-100 text-purple-700 w-1/5 pb-6 hidden md:block">
  <h1 class="text-white text-xl mb-8 mt-3 px-4 font-sans flex justify-between">
    <%= link_to root_path do %>
      <span>Leisure Shelf Playground</span>
    <% end %>
  </h1>

  <div class="mt-4 bg-purple-900 bg-opacity-75 border-t border-b border-white hover:bg-purple-600 hover:bg-opacity-50">
    <%= link_to activities_path,
      class: 'p-2 pl-4 text-white font-semi-bold inline-block w-full h-full' do %>
        <i class="fa-solid fa-list"></i>
        Actividades
    <% end %>
  </div>

  <div class="mt-4 bg-purple-900 bg-opacity-75 border-t border-b border-white hover:bg-purple-600 hover:bg-opacity-50">
    <%= link_to categories_path,
      class: 'p-2 pl-4 text-white font-semi-bold inline-block w-full h-full' do %>
        <i class="fa-solid fa-shapes"></i>
        Categorías
    <% end %>
  </div>

  <div class="mt-4 bg-purple-900 bg-opacity-75 border-t border-b border-white hover:bg-purple-600 hover:bg-opacity-50">
    <%= link_to shelves_path,
      class: 'p-2 pl-4 text-white font-semi-bold inline-block w-full h-full' do %>
        <i class="fa-solid fa-swatchbook"></i>
        Estantes
    <% end %>
  </div>

  <div class="mt-4 bg-purple-900 bg-opacity-75 border-t border-b border-white hover:bg-purple-600 hover:bg-opacity-50">
    <%= link_to series_index_path,
      class: 'p-2 pl-4 text-white font-semi-bold inline-block w-full h-full' do %>
        <i class="fa-solid fa-tv"></i>
        Series de TV
    <% end %>
  </div>

  <div class="mt-4 bg-purple-900 bg-opacity-75 border-t border-b border-white hover:bg-purple-600 hover:bg-opacity-50">
    <%= link_to movies_path,
      class: 'p-2 pl-4 text-white font-semi-bold inline-block w-full h-full' do %>
        <i class="fa-solid fa-film"></i> Películas
    <% end %>
  </div>
</div>

app/views/shared/_topbar.html.erb
<!-- Top bar -->
<div class="border-b flex px-6 py-4 items-center">
  <div class="flex flex-col">
    <div class="text-grey">
      <%= yield :top_text %>
    </div>
  </div>
  <div class="ml-auto hidden md:block">
    <%= yield :action_button %>
  </div>
</div>

app/views/shelves/_form.html.erb
<%= form_with(model: shelf, id: dom_id(shelf)) do |f| %>
  <% if @shelf.errors.any? %>
    <div id="error_explanation">
      <p>
        <%= pluralize(@shelf.errors.count, "error") %> prohibited this shelf from being saved:
      </p>

      <ul class="list-disc text-red-500 mb-4">
        <% @shelf.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="flex flex-row justify-center">
    <div class="flex flex-col flex-grow">
      <%= f.label :name %>
      <%= f.text_field :name, class: 'border-solid border-2 p-2 w-full md:w-3/4 lg:w-5/12', placeholder: 'Nombre' %>
    </div>
  </div>

  <div class="flex flex-row justify-center mt-6">
    <div class="flex flex-col flex-grow">
      <%= f.label :description %>
      <%= f.text_area :description, class: 'border-solid border-2 p-2 w-full md:w-3/4 lg:w-5/12', placeholder: 'Text' %>
    </div>
  </div>

  <div class="flex flex-row mt-4">
    <% button_text = @shelf.new_record? ? 'Guardar' : 'Actualizar' %>
    <%= f.submit button_text, class: 'mt-2 bg-blue-500 text-white font-semibold px-4 py-2 rounded w-full md:w-3/4 lg:w-5/12' %>
  </div>
<% end %>

app/views/shelves/_shelf.html.erb
<%= turbo_frame_tag dom_id(shelf) do %>
  <div class="max-w-xs rounded overflow-hidden my-2 mr-2 bg-gray-200">
    <div class="px-6 py-4">
      <span class="name font-bold text-xl">
        <%= link_to shelf.name, shelf_path(shelf), data: { turbo: false } %>
      </span>
      <small>
        <%= link_to 'Edit', edit_shelf_path(shelf) %>
      </small>
    </div>
  </div>
<% end %>

app/views/shelves/edit.html.erb
<%= turbo_frame_tag dom_id(@shelf) do %>
  <%= render 'form', shelf: @shelf %>
<% end %>

app/views/shelves/index.html.erb
<% content_for :top_text do %>
  <h3>Todas los estantes</h3>
<% end %>

<!--
  En el elemento <button> vemos la forma en que Stimulus trabaja.

  Se definen atributos data-action y data-target con los cual el respectivo controlador
  podrá encontrar este elemento y saber qué hacer y a qué elemento afectar.
-->

<% content_for :action_button do %>
<!--
  El atributo `data-action` está indicando que

  - para el evento `click`
  - usa la función `#toggle`
  - del controlador `form-toggle`

  El controlador lo encuentra por una convención:

    form_toggle_controller.js -> form-toggle

  sin usar el sufijo `_controller.js`

  Por su parte, el atributo `data-target` permite referenciar el elemento
  que queremos manipular desde el controlador.

  Se define indicando el nombre del controlador y el nombre del target;

    form-toggle.TARGET_NAME

  Luego, en el controlador se podrá hacer referencia mediante directivas.
-->
  <button
   class="bg-green-600 hover:bg-green-dark text-white font-bold py-2 px-4 rounded"
   data-action="click->form-toggle#toggle"
   data-target="form-toggl.form"
  >
    Crear Estante
  </button>
<% end %>

<%= turbo_stream_from "shelves" %>

<%= turbo_frame_tag "shelf_form" do %>
<!--
  Con el atributo data-controller-target podemos completar el enlace
  entre controlador y objetivo.
-->
  <div data-form-toggle-target="form" class="hidden">
    <%= render "form", shelf: @shelf %>
  </div>
<% end %>

<div>
  <%= turbo_frame_tag "shelves", class: "flex flex-row flex-wrap" do %>
    <%= render @shelves %>

    <%#= render(ShelfComponent.with_collection(@shelfs)) %>
  <% end%>
</div>

app/views/shelves/new.html.erb
<h1>Shelfs#new</h1>
<p>Find me in app/views/shelfs/new.html.erb</p>

app/views/shelves/show.html.erb
<% content_for :top_text do %>
  <h2>Viendo: <%= @shelf.name %></h2>
<% end %>

<% content_for :action_button do %>
  <%= link_to 'Volver', shelves_path, class: 'bg-blue-500 hover:bg-blue-600 text-white font-bold py-2 px-4 rounded' %>

  <%= link_to 'Editar', edit_shelf_path(@shelf), class: 'bg-yellow-500 hover:bg-yellow-600 text-white font-bold py-2 px-4 rounded' %>
<% end %>

<div class="flex flex-row flex-wrap">
  <%= render(ShelfDetailComponent.new(shelf_detail: @shelf)) %>
</div>